var products = [
  {
    nombre: "Hotel La Sierra",
    estrellas: "3",
    ubicacion: "Cordoba",
    direccion: "calle falsa 123",
    telefono: "123456789",
    tipo: "Standard",
    precio_por_noche: 90,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "Imagenes/Hotel La Sierra.jpg",
    descripcion: "Piscina, desayuno"
  },
  {
    nombre: "Hotel El Mendocino",
    estrellas: "3",
    ubicacion: "Mendoza",
    direccion: "Las Delicias 1343",
    telefono: "987654321",
    tipo: "Standard",
    precio_por_noche: 80.00,
    color: "color-2",
    check: "check2",
    radio: "radio1",
    option: "option2",
    imagen: "http://placehold.it/350x200",
    descripcion: ""
  },
  {
    nombre: "Hotel Howard Jhonson",
    estrellas: "5",
    ubicacion: "Buenos Aires",
    direccion: "Entre Rios 2154",
    telefono: "456123789",
    tipo: "Presidencial",
    precio_por_noche: 299.99,
    color: "color-3",
    check: "check1",
    radio: "radio2",
    option: "option1",
    imagen: "imagenes/Howard Jhonson.jpg",
    descripcion: "Piscina, Piscina climantizada, Desayuno, Restaurante"
  },
  {
    nombre: "Hotel El Mendocino",
    estrellas: "3",
    ubicacion: "Mendoza",
    direccion: "Las Delicias 1343",
    telefono: "987654321",
    tipo: "Standard",
    precio_por_noche: 90.00,
    color: "color-2",
    check: "check2",
    radio: "radio1",
    option: "option1",
    imagen: "http://placehold.it/350x200",
    descripcion: "Deayuno, Piscina"
  },
  {
    nombre: "Hotel Howard Jhonson",
    estrellas: "5",
    ubicacion: "Buenos Aires",
    direccion: "Entre Rios 2154",
    telefono: "456123789",
    tipo: "Premium",
    precio_por_noche: 150.00,
    color: "color-3",
    check: "check3",
    radio: "radio3",
    option: "option2",
    imagen: "imagenes/Howard Jhonson.jpg",
    descripcion: "Piscina, Piscina climantizada, Desayuno, Restaurante"
  },
  {
    nombre: "Hotel RutaAtlantica",
    estrellas: "2",
    ubicacion: "Buenos Aires",
    direccion: "Chacarita 1540",
    telefono: "789123456",
    tipo: "Standard",
    precio_por_noche: 60.00,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "http://placehold.it/350x200",
    descripcion: "desayuno"
  },
  {
    nombre: "Hotel Santos Lugares",
    estrellas: "4",
    ubicacion: "San Martin de los Andes",
    direccion: "Belgrano 450",
    telefono: "321654987",
    tipo: "Premium",
    precio_por_noche: 150.00,
    color: "color-2",
    check: "check2",
    radio: "radio1",
    option: "option1",
    imagen: "http://placehold.it/350x200",
    descripcion: ""
  },
  {
    nombre: "Hotel Loi Suites",
    estrellas: "5",
    ubicacion: "San Martin de los Andes",
    direccion: "Ruta nacional 40, KM 2227",
    telefono: "654987321",
    tipo: "Presidencial",
    precio_por_noche: 350.00,
    color: "color-3",
    check: "check3",
    radio: "radio3",
    option: "option2",
    imagen: "imagenes/loiSuites.jpg",
    descripcion: ""
  },
  {
    nombre: "Hotel Buenos Aires",
    estrellas: "4",
    ubicacion: "CABA",
    direccion: "Corrientes 1442",
    telefono: "117258369",
    tipo: "Premium",
    precio_por_noche: 180.00,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "imagenes/Hotel Buenos Aires.jpg",
    descripcion: "Piscina, cerca del centro, restaurante"
  },
  {
    nombre: "Hotel Cottbus",
    estrellas: "3",
    ubicacion: "San Carlos de Bariloche",
    direccion: "Villegas 444",
    telefono: "369258147",
    tipo: "Standard",
    precio_por_noche: 80.00,
    color: "color-2",
    check: "check2",
    radio: "radio1",
    option: "option1",
    imagen: "http://placehold.it/350x200",
    descripcion: ""
  },
  {
    nombre: "Hotel Cottbus",
    estrellas: "3",
    ubicacion: "San Carlos de Bariloche",
    direccion: "Villegas 444",
    telefono: "258369147",
    tipo: "Standard",
    precio_por_noche: 85.0,
    color: "color-3",
    check: "check3",
    radio: "radio3",
    option: "option2",
    imagen: "http://placehold.it/350x200",
    descripcion: ""
  },
  {
    nombre: "Hotel Howard Jhonson",
    estrellas: "5",
    ubicacion: "Buenos Aires",
    direccion: "Entre Rios 2154",
    telefono: "456123789",
    tipo: "Premium",
    precio_por_noche: 150.00,
    color: "color-3",
    check: "check3",
    radio: "radio3",
    option: "option2",
    imagen: "imagenes/Howard Jhonson.jpg",
    descripcion: "Piscina, Piscina climantizada, Desayuno, Restaurante"
  },
  {
    nombre: "Hotel Buenos Aires",
    estrellas: "4",
    ubicacion: "CABA",
    direccion: "Corrientes 1442",
    telefono: "117258369",
    tipo: "Standard",
    precio_por_noche: 120.00,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "imagenes/Hotel Buenos Aires.jpg",
    descripcion: "Piscina, cerca del centro, restaurante"
  },
  {
    nombre: "Hotel RutaAtlantica",
    estrellas: "2",
    ubicacion: "Buenos Aires",
    direccion: "Chacarita 1540",
    telefono: "789123456",
    tipo: "Standard",
    precio_por_noche: 45.00,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "http://placehold.it/350x200",
    descripcion: "desayuno"
  },
  {
    nombre: "Hotel Loi Suites",
    estrellas: "5",
    ubicacion: "San Martin de los Andes",
    direccion: "Ruta nacional 40, KM 2227",
    telefono: "654987321",
    tipo: "Presidencial",
    precio_por_noche: 320.00,
    color: "color-3",
    check: "check3",
    radio: "radio3",
    option: "option2",
    imagen: "imagenes/loiSuites.jpg",
    descripcion: ""
  },
  {
    nombre: "Hotel La Sierra",
    estrellas: "3",
    ubicacion: "Cordoba",
    direccion: "calle falsa 123",
    telefono: "123456789",
    tipo: "Standard",
    precio_por_noche: 99.99,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "Imagenes/Hotel La Sierra.jpg",
    descripcion: "Piscina, desayuno"
  },
  {
    nombre: "Hotel Cristal",
    estrellas: "4",
    ubicacion: "San Carlos de Bariloche",
    direccion: "Mitre 355",
    telefono: "258147369",
    tipo: "Premium",
    precio_por_noche: 140.00,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "http://placehold.it/350x200",
    descripcion: "Piscina, Piscina climatizada, cerca del Centro"
  },
  {
    nombre: "Hotel Cristal",
    estrellas: "4",
    ubicacion: "San Carlos de Bariloche",
    direccion: "Mitre 355",
    telefono: "258147369",
    tipo: "Standard",
    precio_por_noche: 110.00,
    color: "color-1",
    check: "check1",
    radio: "radio2",
    option: "option3",
    imagen: "http://placehold.it/350x200",
    descripcion: "Piscina, Piscina climatizada, cerca del Centro"
  }                      
  
];

// Resto del código de la lógica del carrito de compras
